---
driver:
  name: dokken
  privileged: true
  chef_version: latest

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: /opt/verifier
  sudo: false

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN dpkg-divert --remove /sbin/initctl
        - RUN ln -sf /sbin/initctl.distrib /sbin/initctl
  - name: debian-8
    driver:
      image: debian:8
      pid_one_command: /lib/systemd/systemd
  - name: centos-7
    driver:
      image: centos:7
      pid_one_command: /lib/systemd/systemd
  - name: centos-6
    driver:
      image: centos:6
      pid_one_command: /sbin/init
  - name: ubuntu-16.04-chef-12
    driver:
      image: ubuntu:16.04
      chef_version: 12.20.3
      pid_one_command: /lib/systemd/systemd
  - name: ubuntu-14.04-chef-12
    driver:
      image: ubuntu:14.04
      chef_version: 12.20.3
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN dpkg-divert --remove /sbin/initctl
        - RUN ln -sf /sbin/initctl.distrib /sbin/initctl
  - name: debian-8-chef12
    driver:
      image: debian:8
      chef_version: 12.20.3
      pid_one_command: /lib/systemd/systemd
  - name: centos-7-chef-12
    driver:
      image: centos:7
      chef_version: 12.20.3
      pid_one_command: /lib/systemd/systemd
  - name: centos-6-chef-12
    driver:
      image: centos:6
      chef_version: 12.20.3
      pid_one_command: /sbin/init
